name: 'CI actions'

on:
  pull_request_target:
    types: opened

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      # - name: Install GH CLI
      #   uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Hello
        run: echo "Hello"

