name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - run: echo ${{ secrets.GITHUB_TOKEN }}

      - name: Close Pull
        run: gh pr close 3
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

