name: 'CI actions'

on:
  pull_request_target:
    types: opened

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: PR No from base
        run: echo ${{ github.event.pull_request.number }}

      - name: github.ref
        run: echo ${{ github.ref }}
        
      - name: head_ref
        run: echo ${{ github.head_ref  }}

      - name: Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Print PR number
        run: echo ${{ github.event.pull_request.number  }}


