name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Install gh
        run: type -p curl >/dev/null || (sudo apt update && sudo apt install curl -y)
             curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg \
             && sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg \
             && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
             && sudo apt update \
             && sudo apt install gh -y


      - name: Close Pull
        run: gh pr close --comment "Auto-closing pull request"
        env:
          GITHUB_TOKEN: ${{ secrets.TEST }}
