name: 'CI actions'

on:
  pull_request:
    types: [opened, edited]

jobs:
  PR_TARGET:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to branch
        uses: actions/checkout@v3

      - name: PR No
        run: echo ${{ github.event.pull_request.number }}

      - name: Github_ref refs/pull/:prNumber/merge
        run: echo ${{ github.ref }}
        
      - name: Head_ref
        run: echo ${{ github.head_ref  }}

      - name: Base Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Print Hello
        run: echo ${{ github.event.pull_request.number  }}

