name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    permissions: write-all
    runs-on: ubuntu-latest
    container: node

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Checkout to base branch
        uses: actions/checkout@v3
        with:
          github-token: ${{ secrets.MY_TOKEN }}
          ref: gh-action

      - name: PRINT FORK
        run: echo "I'm from the fork"

      - run: git config --global --add safe.directory /__w/JavaUltimate2022/JavaUltimate2022
      - run: echo ${{ github.event.pull_request_target }}

      - run: echo run ${{ github.event.repository.name }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref  }}


      - name: Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Print PR number
        run: echo ${{ github.event.pull_request.number  }}

      - name: Close Pull
        run: gh pr close ${{ github.event.pull_request.number }}
        

