name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node:16

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Close Pull
        run: gh pr close --comment "Auto-closing pull request"
        env:
          GH_TOKEN: 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
