name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Checkout to base branch
        uses: actions/checkout@v3
        with:
          repository: EEM86/JavaUltimate2022
          ref: gh-actions

      - run: echo ${{ github.event.pull_request_target }}

      - run: echo run ${{ github.event.repository.name }}
      - run: echo ${{ github.ref }}
      - run: echo ${{ github.head_ref  }}


      - name: Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - run: echo ${{ github.event.pull_request.number  }}

      - run: echo ${{ github.event.pull_request.html_url  }}

      - name: Close Pull
        run: gh pr close ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

