name: 'CI actions'

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  CLOSE_PR:
    runs-on: ubuntu-latest

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Print github.ref
        run: echo ${{ github.ref }}
      - name: Print head_ref
        run: echo ${{ github.head_ref  }}


      - name: Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Print PR number
        run: echo ${{ github.event.pull_request.number  }}

      - name: Close Pull
        run: gh pr close ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
