name: 'CI actions'

on:
  pull_request_target:
    types: opened

jobs:
  PR_TARGET:
    runs-on: ubuntu-latest

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0



      - name: PR No from base
        run: echo ${{ github.event.pull_request.number }}

      - name: Base github.ref
        run: echo ${{ github.ref }}
        
      - name: Base head_ref
        run: echo ${{ github.head_ref  }}

      - name: Base Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Base Print PR number
        run: echo ${{ github.event.pull_request.number  }}

      - name: Checkout to base branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - name: Close Pull
        run: gh pr close ${{ github.event.pull_request.number }} --delete-branch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

