name: 'CI actions'

on:
  pull_request:
    branches:
      - gh-action

jobs:
  challenge_check:
    runs-on: ubuntu-latest
    container: node:16

    env:
      GITHUB_TOKEN: ${{ secrets.TEST }}

    steps:
      - name: Branch checkout
        uses: actions/checkout@v3

      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action
        with:
          gh-cli-version: 2.14.2 # optional, see action.yml for current default

      - name: Close Pull
        run: gh pr close --comment "Auto-closing pull request"

