name: 'CI actions'

on:
  pull_request_target:
    types: [opened, edited]

jobs:
  PRINT_HELLO:
    runs-on: ubuntu-latest

    steps:
      - name: Print ref base branch
        run: echo ${{ github.event.pull_request.github_ref }}

      - name: Print base last commit sha
        run: echo ${{ github.event.pull_request.github_sha }}

      - name: Print ref to merge branch
        run: echo ${{ github.event.number }}
        
      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          ref: "refs/pull/${{ github.event.number }}/merge"

      - name: PR No
        run: echo ${{ github.event.pull_request.number }}

      - name: PR Head_ref
        run: echo ${{ github.event.pull_request.head_ref  }}

      - name: PR Head_ref
        run: echo ${{ github.head_ref  }}

      - name: Read file contents
        id: read_file
        uses: andstor/file-reader-action@v1
        with:
          path: "test.txt"

  CLOSE_PR:
    needs: PRINT_HELLO
    runs-on: ubuntu-latest

    steps:
      - name: Install GH CLI
        uses: dev-hanz-ops/install-gh-cli-action@v0.1.0

      - name: Print github.ref
        run: echo ${{ github.ref }}
      - name: Print head_ref
        run: echo ${{ github.head_ref  }}


      - name: Print PR html
        run: echo ${{ github.event.pull_request.html_url  }}
        
      - name: Print PR head sha
        run: echo ${{ github.event.pull_request.head.sha  }}

      - name: Checkout to branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.github_sha }}

      - name: Close Pull
        run: gh pr close ${{ github.event.pull_request.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
